# Generated by Django 5.1.1 on 2024-09-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тема письма')),
                ('send_time', models.DateTimeField(verbose_name='Дата отправки')),
                ('recieve_time', models.DateTimeField(verbose_name='Дата получения')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('config_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.configuser', verbose_name='Почтовый клиент')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-send_time'],
            },
        ),
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imap_message.messagemodel')),
            ],
        ),
    ]
