# Generated by Django 5.1.1 on 2024-09-20 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mail', models.CharField(blank=True, max_length=64, null=True)),
                ('name_server', models.CharField(max_length=256)),
                ('username_mail', models.CharField(max_length=256)),
                ('pass_mail', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Почтовый ящик',
                'verbose_name_plural': 'Почтовые ящики',
            },
        ),
    ]
